### ISSUE TITLE
Fix LinkedIn integration

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#161]
Hi @cinaaaa,
we are having this LinkedIn integration on our website but it's not working properly. Could you have a look at it and see if you can find a way either fix it or make a new kind of integration? It should always automatically fetch the newest LinkedIn post and display it.
![grafik](https://user-images.githubusercontent.com/49870195/210238043-a74dc3ff-9b8b-47cd-971e-aa88d3638dcf.png)
Thank you!

**Comment by cinaaaa** [comment]
@UJehle
According to https://www.linkedin.com/help/linkedin/answer/a529065/embed-content-from-the-linkedin-feed?lang=en, we can just embed posts by clicking on them and copying their code and it's not possible to have something stream or live-update.
 I was investigating this and there is 3 way to this
- Manually update the LinkedIn post after each post
- Premium embed websites like tag embed and juicer
- Scraping LinkedIn automatically and updating the LinkedIn embed link with our backend ( too complicated and not worth it! )

**Comment by UJehle** [comment]
Thanks Sina for investigating on this. Currently, I think currently the **manual update**, is integrated but even this is not properly working. I was exchanging the links sometimes but it just throws an error. Did you also try this? Was it working for you?

**Comment by cinaaaa** [comment]
> Thanks Sina for investigating on this. Currently, the **manual update**, is integrated but even this is not properly working. I was exchanging the links sometimes but it just throws an error. Did you also try this? Was it working for you?

Where is this feature implemented?! how can I see it?! then I can figure out why it's not working ;)

**Comment by UJehle** [comment]
![grafik](https://user-images.githubusercontent.com/49870195/214262998-be2443bc-6d8f-489a-adf7-6951047d64f6.png)
it should be here (in the _index.md_ (line 182) and _index.html_ (line 168ff.))
