### ISSUE TITLE
Improve page loading speed 

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#167]
Hi @cinaaaa ,
I just checked the page loading speed. It seems like we need to improve the performance.
**Desktop:** 
![grafik](https://user-images.githubusercontent.com/49870195/210514816-62339cda-ccdf-4b99-9d11-45a5c0f0f67f.png)

**Smartphone:**
![grafik](https://user-images.githubusercontent.com/49870195/210514934-0b573a67-c627-4fbe-8c7e-4468c31430d9.png)

Especially for smartphone, it's very low at the moment. 
You can check the insights here: https://pagespeed.web.dev/report?url=https%3A%2F%2Fplan4better.de%2F&form_factor=mobile

We should aim to reach a performance >90. Would be great if you could try to achieve this.

**Checklist**

- [ ] Desktop performance >90
- [ ] Smartphone performance >90

**Comment by UJehle** [comment]
@dilaann & @iremkapucuoglu if you are having some time in between, you could assist here in checking the link above, which images are too big:
![Image](https://user-images.githubusercontent.com/49870195/234230051-c29ef24f-6e62-41d7-9113-64f82bbd7ea1.png)
And then reduce their size with Birme. Finding a good balance between image size and beeing not blurry on the website.
If you find images that are in PNG or JPG, you can convert them to WEBP, that also helps to improve the page loading speed.

**Comment by UJehle** [comment]
Thanks @dilaann for improving the images. They are not in main branch yet, but I just checked the performance of the dev-branch: https://pagespeed.web.dev/analysis/https-dev-plan4better-de/i9cds7i492?form_factor=mobile
It already improved 🚀 and now shows further optimization potential in adjusting images sizes. Seems like some of the images are too big in size. You can find them in this section:
![grafik](https://github.com/goat-community/p4b-website/assets/49870195/ce799075-4b41-4bbc-9465-40bb5beaf53b)
Would be great if you could also have a look at them and reduce them to a suitable size (big enough to not show blurry but not bigger than needed).

**Comment by EPajares** [comment]
Check video loading times as this might be the slowest. Is there something else here @UJehle or can we close it

**Comment by UJehle** [comment]
@EPajares there are some open JavaScript issues that should be addressed. I am not sure who could take this over and have a look?

**Comment by UJehle** [comment]
As we are planning to move to another website provider soon, I will now put this on hold for now.
