### ISSUE TITLE
"All the way up" button sits on the text

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#174]
Hi @cinaaaa,
in the [tutorial](https://plan4better.de/tutorials/isochrone/) section of our website, we are having this green button that brings you all the way up to the beginning of the page. Anyhow, when I scroll down to the very bottom, the button sits on top of the text which is a bit ugly. Furthermore, the button hinders the users from clicking on the link "isochrone tutorial" in the shown screenshot. 
![grafik](https://user-images.githubusercontent.com/49870195/211592987-a591f2d4-270d-445a-8e04-d4aec915ad3c.png)

Could you move the button a bit down when the user is at the bottom of the page?

**Comment by UJehle** [comment]
Hi @cinaaaa , somehow this button is now completely gone. I wanted to keep it but just move it a bit that it's not sitting on the text. Could you please bring it back and fix this?

**Comment by cinaaaa** [comment]
Thanks, @UJehle  for reporting this, But I wasn't able to re-produce this bug in both chrome and firefix and it's working for me in all the diffrent sizes 🤔 can you provide more details or maybe screen-shots?!

**Comment by UJehle** [comment]
Hi @cinaaaa , here is a screencast: https://www.awesomescreenshot.com/video/14837064?key=54e5f627e14eda365a602e81906215ae
(this is Firefox) 
As you can see, there is no "all the way up" button.

**Comment by UJehle** [comment]
I just double checked. The button is only missing for the blogposts. For the "docs" and "tutorials" it's there.

But in the "docs" section I discovered something else:
![grafik](https://user-images.githubusercontent.com/49870195/219048488-7cb668f6-847e-478f-80c8-2555871122b8.png)
Do you know where this icon comes from? I think it's a mistake that it sits there.

**Comment by cinaaaa** [comment]
@UJehle  Yeah, I think so, Ok NO PROBLEM, I'll fix it

**Comment by UJehle** [comment]
Thanks. It already looks way better now. Just in some cases, the issue is still there that the "all the way up" button is sitting on the text and thus preventing links to be clicked, e.g. here 
https://www.awesomescreenshot.com/video/14874705?key=c64c3404369677feb3f174dcaf8a37a0

**Comment by cinaaaa** [comment]
@UJehle  Aha, just get it what you meant before, sure I'll fix this too.

**Comment by UJehle** [comment]
Thanks for the PR https://github.com/goat-community/p4b-website/pull/196. This looks good.
