### ISSUE TITLE
P4B-dev site not working

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#182]
It shows a build error in Netlify: "This site uses an unsupported build image. [Update it](https://app.netlify.com/sites/p4b-dev/settings/deploys#build-image-selection) to enable builds." 
@cinaaaa can you investigate on this?

**Comment by cinaaaa** [comment]
@UJehle Just fixed.

**Comment by UJehle** [comment]
Hi @cinaaaa,
thanks for having a look at and fixing this. Looks good!

**Comment by UJehle** [comment]
Hi @cinaaaa , I am not sure what is the reason for this but the dev-page is again not loading properly. Could you have a look and investigate on this? 
![grafik](https://user-images.githubusercontent.com/49870195/222831470-53772ea4-98c9-4329-99ad-4ff561514f14.png)
