### ISSUE TITLE
Improve LinkedIn integration

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#188]
Hi @cinaaaa,
we just checked the website on different browsers and seems like the LinkedIn integration is not working properly on all of them. Especially in Firefox it's quite ugly (see Screencast: https://www.awesomescreenshot.com/video/14772981?key=665bde08a0e6cf6401b4ab2cd82ea6c7)
Is it possible to remove the white space on top of the iframe? And to remove the scroll bar on the right? Both are quite ugly. 
Also the logo of LinkedIn is not loading. Is this fixable?

**Comment by EPajares** [comment]
remove the linkedin integration

**Comment by UJehle** [comment]
Hi @cinaaaa, I just checked you changes. 

In my localhost, the twitter images are very blurry. I am not sure if this gets better when bringing it online. 
![Image](https://user-images.githubusercontent.com/49870195/228189127-20b9446e-8b82-4905-81e0-2c54b40c56e7.png)
Let's review this again when it's online and see if we need to make some adjustments.

**Comment by cinaaaa** [comment]
Oh, that's weird but I guess it's your network problem because we don't have access to do any changes on the Twitter iframe or figures :( I think we can test it again when it's online 
@UJehle
