### ISSUE TITLE
Fix image in /docs/walkability_population_heatmap/

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#190]
Hi @dilaann,
this image is not perfect. Somehow there is a black line and the legend is cut. Could you improve this one? 
![grafik](https://user-images.githubusercontent.com/49870195/218502816-6ccc752c-14ac-4127-959b-9465f56369d3.png)

**Comment by dilaann** [comment]
Hi, @UJehle  I made a commit to PR. --> https://github.com/goat-community/p4b-website/pull/184/commits/617112c8ca4cf41d5359aaa7357acf43af0b904f 

And it looks like this now: 

German:
![image](https://user-images.githubusercontent.com/80716601/219150504-a670bbdb-6796-4f4d-8065-122d50845d47.png)

English:
![image](https://user-images.githubusercontent.com/80716601/219150730-f05eb177-be56-4739-a739-90d600636fb0.png)

**Comment by UJehle** [comment]
Thanks @dilaann ! True, there seems to be a bug. I just opened an issue on this. Can you for now maybe just put a text box in PowerPoint on top that the German version also contains the full name "Leichter Erreichbarkeitsüberschuss"?

**Comment by dilaann** [comment]
Okay, I created a new one, how is it now? @UJehle 



![Image](https://user-images.githubusercontent.com/80716601/219414195-6de1d094-5006-451e-abf6-fbd542299873.png)

Thanks

**Comment by UJehle** [comment]
That's perfect! Thanks :)

**Comment by dilaann** [comment]
No worries, I made [commit.](https://github.com/goat-community/p4b-website/pull/184/commits/3161f9e0c4170b469f183f51a054b06fe0201d46)
@UJehle
