### ISSUE TITLE
Map4Citizens Page

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/p4b-website#201]
Review the "steps fold":
Current version: step follow zigzag
For better usability the steps would be align (figma draft) 
Discuss wether the implementation might generate bugs and wether is worth align or keep it in zigzag.
Whatever decided, it should be the same for all pages.

**Comment by UJehle** [comment]
Hi @AnaSasso, I am just tidying up the issues. I think we can close this issue for now and soon rather think about building a new website from scratch.
