### ISSUE TITLE
[website] Review Steps Card GOAT page

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/p4b-website#206]
- Align steps card
- use reference m4c steps
- accordion>>>card

**Comment by AnaSasso** [comment]
![Image](https://user-images.githubusercontent.com/116002158/237054696-5d9f6ef2-d261-43f0-9edc-7a8ceb458733.png)

**Comment by UJehle** [comment]
Hi @AnaSasso, I am just tidying up the issues. I think we can close this issue for now and soon rather think about building a new website from scratch.
