### ISSUE TITLE
[website] M4C Page

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/p4b-website#207]
[Figma](https://www.figma.com/file/SmmQgQZ9QvWwg62NBlJcN8/P4B-Website-local?type=design&node-id=234%3A1849&t=VnlkgtfUQROdrzZN-1)

- [x] M4C Page Design
- [x] Steps fold> user current GOAT page logic
- [x] Mobile version

**Comment by AnaSasso** [comment]
![Image](https://user-images.githubusercontent.com/116002158/234233735-133425ec-231e-4249-81bd-e33fc8ea8b31.png)

**Comment by AnaSasso** [comment]
![Image](https://user-images.githubusercontent.com/116002158/237055131-c3ba92fc-9b2b-49d2-abf3-e86514f87577.png)

**Comment by AnaSasso** [comment]
**Mobile version**

<img src="https://github.com/goat-community/p4b-website/assets/116002158/cd0ca74d-a87b-4b69-9979-aad9ec741af1" width=50% height=50%>

**Comment by UJehle** [comment]
Awesome!
Next steps:

- [ ] @UJehle put everything from Figma in GitHub
- [ ] @cinaaaa Design updates
- [ ] @UJehle & @AnaSasso final check
- [ ] @UJehle release

**Comment by AnaSasso** [comment]
Mockups updated

![Image](https://github.com/goat-community/p4b-website/assets/116002158/c9cd5163-9fdb-409d-a1b9-a11422e07f06)

**Comment by UJehle** [comment]
@cinaaaa please let me know when the design updates are done. Would be nice to have them soon.
