### ISSUE TITLE
"Reference" Review, Release

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/p4b-website#215]
Final Review for reference page:

> From design: I'm making suggestions, front input is welcome.
> Suggestions in the comments

**Comment by AnaSasso** [comment]
>issue: It's unclear for user to click on the images to full view.
>solution: add interaction to gallery card
>suggestion: 1.Zoom in image while hovering>or 2.Card with shadow while hovering (0>35%)

<img width="1166" alt="Screenshot 2023-04-16 at 16 59 03" src="https://user-images.githubusercontent.com/116002158/232338861-b28835cc-935f-478d-90a0-4612243217b5.png">

**Comment by UJehle** [comment]
I actually like the look of this section at the moment. The transparent background looks nicer than the white one.
