### ISSUE TITLE
[P4B website] Improve mobile version

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#218]
Currently, many people are opening our website on the mobile phone, but many pages don't look super nice on the smartphone. So we should invest some time to improve the mobile version. 

@AnaSasso as we discussed, could you have a look at it when you have time and make a draft in Figma on how to improve it.

**Comment by EPajares** [comment]
Make list of pages that can/should be improved. Fix the homepage first.

**Comment by UJehle** [comment]
- [ ] landing page: show pictures instead of videos if the user opens it with smartphone
- [ ] reference page: use the width of the page better, currently we have quite big white spaces
- [ ] ... to be continued ...

**Comment by UJehle** [comment]
Performance 2023-05-11:
![Uploading grafik.png…]()
Aim: improving! 🚀

**Comment by AnaSasso** [comment]
<img src="https://github.com/goat-community/p4b-website/assets/116002158/2a456809-09b7-4964-94b6-89494b67c563" width=30% height=30%>
