### ISSUE TITLE
[P4B Website] Search box doesn't work properly

### ISSUE THREAD

**Issue by dilaann** [goat-community/p4b-website#222]
Hello, I realized something while I was working on the website. In the [blog ](https://plan4better.de/en/blog/) section, we have a search box but it only searches for some specific keywords. I believe it would be more efficient if this box works like ctrl + f and finds all keywords or titles.

Example:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/80716601/235915097-da5b3f12-33e5-44de-99a8-b454423e0943.png">

**Comment by cinaaaa** [comment]
@UJehle Just fixed the search to only search in the blog and title of the content for a more accurate search.

**Comment by UJehle** [comment]
@cinaaaa I just checked it. Seems like all the blog posts are now listed several times in the results.
![grafik](https://user-images.githubusercontent.com/49870195/236687187-8a660fb8-e25b-4f15-af9c-e34b565e4a97.png)

Is it possible to still include a search on the references page? But to limit it to the references while the blog search is limited to the blog content?

**Comment by cinaaaa** [comment]
> @cinaaaa I just checked it. Seems like all the blog posts are now listed several times in the results. ![grafik](https://user-images.githubusercontent.com/49870195/236687187-8a660fb8-e25b-4f15-af9c-e34b565e4a97.png)
> 
> Is it possible to still include a search on the references page? But to limit it to the references while the blog search is limited to the blog content?

Hi @UJehle thanks for mentioning, I will try to implement this today but I can't promise that it's possible, there are some limitations by Hugo.
I'll look for solutions in alternative ways.

**Comment by cinaaaa** [comment]
<img width="1259" alt="Screenshot 2023-05-08 at 11 27 54" src="https://user-images.githubusercontent.com/42252572/236762275-67cb52ae-968a-4a0f-8be9-ec9ea61f26ea.png">
@UJehle BTW, I tried to search for "retr" and didn't see the result you've attached.
I think the master is not updated with the development.

**Comment by UJehle** [comment]
Now it looks good! Thanks a lot. 
Will merge it into master soon.
