### ISSUE TITLE
Remove Twitter plugin

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#242]
Twitter changed it's API access. Due to this, the Twitter plugin on our landing page is not working anymore:
![grafik](https://github.com/goat-community/p4b-website/assets/49870195/c5f73feb-a10d-4823-be6e-6ea08314b2f7)
As Twitter anyhow is not the "place to be" anymore, I think we should just remove the plugin from the website. 
@baghdasarovnorayr could you do this for me? 

Branch to derive: development

**Comment by baghdasarovnorayr** [comment]
https://github.com/goat-community/p4b-website/pull/243
